trigger:
  - feature/azure-pipeline

stages:
  - stage: test
    jobs:
      - job: test_azure_pipeline
        displayName: "Test Pipeline"
        pool:
          vmImage: "ubuntu-18.04"
        steps:
          - checkout: self
          - task: HelmInstaller@1
            displayName: Install Helm
            inputs:
              helmVersionToInstall: "latest"
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/feature/azure-pipeline')
