trigger:
  - feature/azure-pipeline

stages:
  - stage: testing
    jobs:
      - job: tsaving_dashboard_test_pipeline
        displayName: "Tsaving Dashboard Test Pipeline"
        pool:
          vmImage: "ubuntu-18.04"
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: baitregistry

          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              repository: baitregistry.azurecr.io/tsaving-dashboard
              dockerfile: 'Dockerfile'
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: baitregistry
              tags: |
                latest

          - task: HelmInstaller@1
            displayName: Install Helm
            inputs:
              helmVersionToInstall: "latest"

          - task: HelmDeploy@0
            displayName: Helm deploy
            inputs:
              connectionType: "Kubernetes Service Connection"
              azureResourceGroup: ba-it-tools
              kubernetesCluster: ba-it-aks-cluster
              kubernetesServiceEndpoint: baitkubernetescluster
              command: upgrade
              chartType: filepath
              chartPath: tsaving-dashboard
              releaseName: tsaving-dashboard-testing
              install: true
              waitForExecution: false

        condition: eq(variables['Build.SourceBranch'], 'refs/heads/feature/azure-pipeline')
