trigger:
  - feature/azure-pipeline
  - develop
  - master

pr: 
  - develop

stages:
  - stage: testing
    jobs:
      - job: tsaving_dashboard_test_pipeline
        displayName: "Tsaving Dashboard Test Pipeline"
        pool:
          vmImage: "ubuntu-18.04"
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: baitregistry

          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              repository: tsaving-dashboard
              dockerfile: 'Dockerfile'
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: baitregistry
              tag: $(Build.BuildId)

          - task: HelmInstaller@1
            displayName: Install Helm
            inputs:
              helmVersionToInstall: 3.3.0

          - task: HelmDeploy@0
            displayName: Helm deploy
            inputs:
              connectionType: "Kubernetes Service Connection"
              azureResourceGroup: ba-it-tools
              kubernetesCluster: ba-it-aks-cluster
              kubernetesServiceEndpoint: baitkubernetescluster
              command: upgrade
              chartType: filepath
              chartPath: tsaving-dashboard
              chartName: tsaving-dashboard
              releaseName: tsaving-dashboard
              overrideValues: "image.tag=$(Build.BuildId)"
              install: true
              waitForExecution: false

        condition: startsWith(variables['Build.SourceBranch'], 'refs/')
